package com.techyourchance.coroutines.home

enum class ScreenReachableFromHome(val description: String) {
	UI_THREAD_DEMO("UI Thread"),
	BACKGROUND_THREAD_DEMO("Background Thread"),
	BASIC_COROUTINES_DEMO("Basic Coroutines"),
	EXERCISE_1("Exercise 1"),
	EXERCISE_1_SOLUTION("Exercise 1 Solution"),
	COROUTINES_CANCELLATION_DEMO("Coroutines Cancellation"),
	EXERCISE_2("Exercise 2"),
	EXERCISE_2_SOLUTION("Exercise 2 Solution"),
	CONCURRENT_COROUTINES_DEMO("Concurrent Coroutines"),
	SCOPE_CHILDREN_CANCELLATION_DEMO("Scope Children Cancellation"),
	EXERCISE_3("Exercise 3"),
	EXERCISE_3_SOLUTION("Exercise 3 Solution"),
	SCOPE_CANCELLATION_DEMO("Scope Cancellation"),
	VIEWMODEL_DEMO("ViewModel"),
	EXERCISE_4("Exercise 4"),
	EXERCISE_4_SOLUTION("Exercise 4 Solution"),
	DESIGN_DEMO("Design Demo"),
	EXERCISE_5("Exercise 5"),
	EXERCISE_5_SOLUTION("Exercise 5 Solution"),
	COROUTINES_CANCELLATION_COOPERATIVE_DEMO("Coroutines Cancellation Cooperative"),
	COROUTINES_CANCELLATION_COOPERATIVE_2_DEMO("Coroutines Cancellation Cooperative 2"),
	EXERCISE_6("Exercise 6"),
	EXERCISE_6_SOLUTION("Exercise 6 Solution"),
	NON_CANCELLABLE_DEMO("Non-Cancellable"),
	EXERCISE_8("Exercise 8"),
	EXERCISE_8_SOLUTION("Exercise 8 Solution"),
	EXERCISE_9("Exercise 9"),
	EXERCISE_9_SOLUTION("Exercise 9 Solution"),
	UNCAUGHT_EXCEPTION_DEMO("Uncaught Exception"),
	EXERCISE_10("Exercise 10"),
	EXERCISE_10_SOLUTION("Exercise 10 Solution")
}
